name: webserver_top_2022
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  shelf: ^1.3.2
  shelf_static: ^1.1.1
  shelf_router: ^1.1.3
  shelf_cors_headers: ^0.1.3
  sqflite_common_ffi: ^2.1.1+1
  sqflite_common: ^2.2.1+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
